### Spring Boot Settings ###

# In order to use CustomPineconeVectorStore, correctly to handle indexes created by LangChain
spring.main.allow-bean-definition-overriding=true


### Spring AI OpenAI Settings ###

# Either set in the environment or provide in a `.env` file at the root
spring.ai.openai.api-key=${OPENAI_API_KEY}

spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.chat.options.temperature=1.0
spring.ai.openai.embedding.options.model=text-embedding-3-small
spring.ai.openai.embedding.options.dimensions=1536


### Spring AI Pinecone Settings ###

spring.ai.vectorstore.pinecone.contentFieldName=text

# Either set in the environment or provide in a `.env` file at the root
spring.ai.vectorstore.pinecone.apiKey=${PINECONE_API_KEY}

# Either amend defaults as required or set them in the environment
spring.ai.vectorstore.pinecone.environment=${PINECONE_ENVIRONMENT:aped-4627-b74a}
spring.ai.vectorstore.pinecone.projectId=${PINECONE_PROJECT_ID:moalxso}
spring.ai.vectorstore.pinecone.indexName=${PINECONE_INDEX_NAME:ou-comp-it-degree}
spring.ai.vectorstore.pinecone.namespace=${PINECONE_NAMESPACE:ou-comp-it-degree}

# Default topK for similarity search - amend as required
spring.ai.vectorstore.pinecone.topK=20


### App Settings ###

# Debug mode for [DEBUG_LOG] statements
app.debug=true

# Folders to scan for documents
app.folderNames=
# app.folderNames=M255,M257,M256,M263,M359,M362,M363,TM354

# Number of references to show per answer
app.referenceLimit=10